#!/bin/bash
#  ——————————————————————————————————————————————————————————————————————
#  Progetto BreadCaml / The BreadCaml Project
#  Copyright (C) 21-Apr-2026 Piero Furiesi
#  
#  Questo  programma  è software  libero;  può  essere ridistribuito  e/o
#  modificato nei termini della licenza GNU GPL ver. 2,  come specificato
#  nel file LICENZA-it nella cartella principale del progetto.
#  
#  This program is  free software; you can redistribute  it and/or modify
#  it under the terms of the GNU  General Public License (GPL) ver. 2, as
#  specified in the LICENSE-en file in the project root folder.
#  ——————————————————————————————————————————————————————————————————————

# depends.asm generator for stdlib_*.asm routines.
# See <project_root>/src/asm/CODING_RULES

# Input and output files
OUTFILE="$1"
shift
INFILE="$@"

# sed program to extract deps
NAME='[a-zA-Z](_?[a-zA-Z0-9])*'
ROUT="caml_$NAME"
IFDEF='^[ \t]*!ifdef[ \t]+caml_PRIM__'
FALLTH='^[^;]*;+[ \t]*fallthrough[ \t]+'
SEDPROGRAM="
  /$IFDEF/, /^}/ {
  /$IFDEF/ {                   # First line:
    s/$IFDEF($ROUT).*$/\1 \"/  #  isolate the routine name, add quote
    h                          #  copy the line to the hold space
    d                          #  delete it and start next cycle
  }
  /^}/ {                       # Last line:
    g                          #  get the whole held text; add quote
    a \"
    p                          #  print routine name followed by deps
    d                          #  delete all and start next cycle
  }
                               # Lines in between:
  s/$FALLTH($ROUT).*$/ \1/i    #  extract dep from fallthrough comment
  s/;.*$//g                    #  remove other ACME comments
  s/.*($ROUT)(__$NAME)?/§\1/g  #  prepend § to each dep
  /§/! d                       #  if no deps, delete and start next cycle
  s/[^§]*§($ROUT)[^§]*/\1 /g   #  remove § and text between deps
  H                            #  append deps to the hold space
}"

# Init DEPS array
declare -A DEPS="($(sed -s -n -E "$SEDPROGRAM" $INFILE))"

# Remove self deps and fake deps (any caml_xyz which is not a routine)
for ROUTINE in ${!DEPS[@]}; do
    DEPLIST=''
    for DEP in ${DEPS["$ROUTINE"]}; do
	# ${VAR+string} expands to string if VAR is set, to '' if unset
	[[ $DEP != $ROUTINE && ${DEPS[$DEP]+x} ]] && DEPLIST+="$DEP "
    done
    DEPS["$ROUTINE"]="$DEPLIST"
done

# Calculate the transitive closure of all deps (breadth-first visit)
declare -A TRCLOS
declare -Ai VISITED
declare -a QUEUE
for ROUTINE in ${!DEPS[@]}; do
    VISITED=()
    QUEUE=()
    QHEAD=0
    for DEP in ${DEPS["$ROUTINE"]}; do
	VISITED["$DEP"]=1
	QUEUE+=("$DEP")
    done
    while (( QHEAD < ${#QUEUE[@]} )); do
	NODE="${QUEUE[$QHEAD]}"
	(( QHEAD++ ))
	for DEP in ${DEPS["$NODE"]}; do
	    if ! (( ${VISITED[$DEP]} )); then
		VISITED["$DEP"]=1
		QUEUE+=("$DEP")
	    fi
	done
    done
    TRCLOS["$ROUTINE"]=$(printf "%s\n" ${!VISITED[@]})
done

# Generate the output file
{   echo ";; AUTO-GENERATED FILE - DO NOT EDIT"
    echo ";; Generated $(date -Iseconds) by $0"
    echo ""
    for ROUTINE in $(printf "%s\n" ${!DEPS[@]}|sort); do
	[[ ${TRCLOS[$ROUTINE]} ]] && {
            echo "!ifdef caml_PRIM__$ROUTINE {"
            for DEP in $(printf "%s\n" ${TRCLOS[$ROUTINE]}|sort); do
		echo "  !set caml_PRIM__$DEP=1"
            done
            echo "}"
            echo ""
	}
    done
} > "$OUTFILE"
